services:
  api_impar:
    container_name: api_impar
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./
          action: rebuild 
          target: ./app/